version: 2
jobs:
  docker:
    - image: ubuntu
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: bash makedeb.sh
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: dpkg -i startxcli.deb && startxcli
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test