version: 2
jobs:
  build:
    steps:
      - checkout
      - run: bash makedeb.sh
  test:
    steps:
      - checkout
      - run: dpkg -i startxcli.deb && startxcli
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test